version: '3.7'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - api
      - dev
      - test
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
    ports:
      - '8000:5432'
  webapp:
    container_name: webapp
    build:
      context: './webapp'
    expose:
      - 5000
  api:
    container_name: api
    image: applada
    build: 
      context: './api'
    command: bash -c "rm -f tmp/pids/server.pid && (rake db:setup && rake db:migrate || rake db:migrate) && rails server --binding=0.0.0.0 --port=80 -e production"
    environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        RAILS_ENV: production
    volumes:
      - ./tmp/api:/tmp
    expose:
       - 80
    depends_on:
      - db
  dev:
    container_name: dev
    image: applada
    build: 
      context: './api'
    command: bash -c "rm -f tmp/pids/server.pid && (rake db:setup && rake db:migrate || rake db:migrate) && rails server --binding=0.0.0.0 --port=80 -e development"
    environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        RAILS_ENV: development
    volumes:
      - ./api:/api
      - ./tmp/dev:/api/tmp
    expose:
       - 80
    depends_on:
      - db
      - api
  test:
    container_name: test
    image: applada
    build: 
      context: './api'
    command: bash -c "rm -f tmp/pids/server.pid && (rake db:setup && rake db:migrate || rake db:migrate) && rails server --binding=0.0.0.0 --port=80 -e test"
    environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        RAILS_ENV: test
    volumes:
      - ./api:/api
      - ./tmp/test:/api/tmp
    expose:
       - 80
    depends_on:
      - db
      - api