version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./tmp/app:/var/lib/postgresql/data
    ports:
      - '8001:5432'
  api:
    build: 
      context: './api'
      args:
        API_IP: '0.0.0.0'
        API_PORT: 8000
    command: bash -c "rm -f tmp/pids/server.pid && (rake db:setup && rake db:migrate || rake db:migrate) && rails server --binding=0.0.0.0 --port=8000 -e test"
    environment:
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api:/api
    ports:
      - '80:8000'
    depends_on:
      - db